[package]
name = "rust_prompt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
